website/auth.py
from flask import *
from modules.instaloader import Instaloader, Profile, instaloader
from urllib.parse import unquote
import requests
from io import BytesIO
import base64
import asyncio
import aiohttp

auth = Blueprint('auth', __name__)
instance = Instaloader()


def get_code():
    n=1
    code = ""
    try:
        while n<=6:
            code += request.form[f'number{n}']
            n+=1            
        return code
    except Exception as e:
        print("there was an error") 


def abbvr_number(n):
    """Convierte un número a un formato abreviado con 'k', 'M', 'B'."""
    if n < 1000:
        return str(n)
    elif 1000 <= n < 1000000:
        return f"{n/1000:.0f}k"
    elif 1000000 <= n < 1000000000:
        return f"{n/1000000:.0f}M"
    else:
        return f"{n/1000000000:.0f}B"

class Unfollower:
    def __init__(self, username, followers, followees):
        self.username = username
        self.profile_pic_blob = None
        self.isVerified = False
        self.followers = followers
        self.followees = followees
    
    def getisVerified(self):
        return self.isVerified
    
    def setIsVerified(self):
        self.isVerified = True
    
    async def fetch_profile_pic(self):
        try:
            profile = Profile.from_username(instance.context, self.username)
            if profile and profile.profile_pic_url:
                profile_pic_url = unquote(profile.profile_pic_url)
                async with aiohttp.ClientSession() as session:
                    async with session.get(profile_pic_url) as response:
                        if response.status == 200:
                            self.profile_pic_blob = await response.read()
                            return True
                        else:
                            print(f"Error fetching profile pic for {self.username}: HTTP status code {response.status}")
                            return False
            else:
                print(f"Error fetching profile pic for {self.username}: Profile or profile_pic_url is None")
                return False
        except Exception as e:
            print(f"Error fetching profile pic for {self.username}: {str(e)}")
            return False

    def get_profile_pic_data_uri(self):
        if self.profile_pic_blob:
            return f"data:image/jpeg;base64,{base64.b64encode(self.profile_pic_blob).decode('utf-8')}"
        else:
            return None

    def to_dict(self):
        return {
            'username': self.username,
            'followers': self.followers,
            'followees': self.followees,
            'profile_pic_data_uri': self.get_profile_pic_data_uri(),
            'is_Verified': self.getisVerified()
        }

def create_profile(username):
    try:
        profile = Profile.from_username(instance.context, username)
        profile_pic_url = unquote(profile.profile_pic_url) if profile.profile_pic_url else None
        full_name = profile.full_name
        Followers = profile.followers
        Followees = profile.followees
        Posts = 0
        session['full_name'] = full_name
        session['Followees'] = abbvr_number(Followees) 
        session['Followers'] = abbvr_number(Followers)
        session['profile_pic'] = profile_pic_url

        for post in profile.get_posts():
            Posts += 1
        session['Posts'] = abbvr_number(Posts)   
        
        return True
    except Exception as e:
        flash(f"Error creating profile: {str(e)}", category="error")
        return False

async def who_doesnt_follow():
    try:
        profile = Profile.from_username(instance.context, session.get('username'))
        profile_pic_url = unquote(profile.profile_pic_url) if profile.profile_pic_url else None
        session['profile_pic'] = profile_pic_url
        followees = set(profile.get_followees())
        followers = set(profile.get_followers())
        not_following_you = followees - followers

        unfollowers = []
        tasks = []
        
        for user in not_following_you:
            unfollower = Unfollower(user.username, abbvr_number(user.followers), abbvr_number(user.followees))
            if user.is_verified:
                unfollower.setIsVerified()
            tasks.append(asyncio.create_task(unfollower.fetch_profile_pic()))
            unfollowers.append(unfollower)

        await asyncio.gather(*tasks)

        return [unfollower.to_dict() for unfollower in unfollowers]
    except instaloader.ProfileNotExistsException:
        flash("Error")
        return []

@auth.route('/unfollowers', methods=['GET', 'POST'])
def unfollowers():
    if "username" in session:
        username = session.get('username')
        unfollowers = asyncio.run(who_doesnt_follow())
        if unfollowers:
            return render_template('user_profile.html', not_following_you=unfollowers, username=username)
        else:
            flash("No unfollowers found or an error occurred", category="error")
            return render_template('login.html', is_2fa_required=False)
    else:
        flash("You need to log in first", category="error")
        return redirect(url_for('auth.login'))

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['user_input']
        password = request.form['password_input']
       

        

        try:
            instance.login(username, password)
            session['username'] = username
            if create_profile(username):
                return redirect(url_for('views.main'))
        except instaloader.TwoFactorAuthRequiredException:
            session['is_2fa_required'] = True
            session['username'] = username
            return render_template('code_2FA.html',username = username)
        except instaloader.BadCredentialsException:
            flash("Invalid username or password. Please try again.", category="error")
            return render_template('login.html')
    return render_template('login.html')



@auth.route('/code_2fa',methods=['POST','GET'])
def code_2fa():
    if "username" in session:
        try:
            username = session.get('username')
            print(username)
            two_factor_code = get_code()
            print(two_factor_code)
            instance.two_factor_login(two_factor_code)

            if create_profile(username):
                return redirect(url_for('views.main'))
        except instaloader.BadCredentialsException as e:
                flash("Invalid 2FA code. Please try again.", category="error")
                print(e)
                return redirect(url_for('auth.login'))


    else:
        flash("No 2fa pending.", category="error")
        return redirect(url_for('auth.login'))


@auth.route('/profile-pic')
def profile_pic():
    profile_pic_url = session.get('profile_pic')
    if profile_pic_url:
        try:
            response = requests.get(profile_pic_url)
            if response.status_code == 200:
                return send_file(BytesIO(response.content), mimetype='image/jpeg')
            else:
                return '', 404  # Handle appropriately if profile pic retrieval fails
        except Exception as e:
            print(f"Error fetching profile pic: {str(e)}")
            return '', 404
    return '', 404



@auth.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))



@auth.route('/main')
def main():
    if "username" in session:
        username = session.get('username')
        return render_template('main.html', username=username)
    else:
        flash("You need to log in first", category="error")
        return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template, session, redirect, url_for
import time


views = Blueprint('views', __name__)

@views.route('/')
def splash_page():
    session.clear()
    return render_template('splash_page.html')



@views.route('/user_profile')
def user_profile():
    if "username" in session:
        username = session.get('username')
        profile_pic_url = session.get('profile_pic')
        full_name = session.get('full_name')
        Followees = session.get('Followees')
        Followers = session.get('Followers')
        Posts = session.get('Posts')
        return render_template('user_profile.html', username=username,full_name = full_name, Followers = Followers, Followees = Followees, profile_pic_url = profile_pic_url, Posts = Posts)
    else:
        return redirect(url_for('auth.login'))


@views.route('/main')
def main():
    if "username" in session:
        username = session.get('username')
        profile_pic_url = session.get('profile_pic')
        full_name = session.get('full_name')
        Followees = session.get('Followees')
        Followers = session.get('Followers')
        Posts = session.get('Posts')
        return render_template('main.html', username=username,full_name = full_name, Followers = Followers, Followees = Followees, profile_pic_url = profile_pic_url, Posts = Posts)
    
    else:
        return redirect(url_for('auth.login'))    

@views.route('/terms_of_use')
def terms_of_use():
    return render_template('terms_use.html')    

website/templates/code_2FA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>2FA Code</title>
    <link rel="stylesheet" href="{{url_for('static', filename = 'styles/2FA.css')}}">
</head>
<body>
    <div class="modal_code">
    <form method="POST" action= "{{url_for('auth.code_2fa')}}">
        <i class="fa-solid fa-lock"></i>
        <small>Enter the 6-digit code generated by your authentication app for {{username}}.</small>
        <input type="text" maxlength="1" pattern="[0-9]" class = "number-input" name="number1"required>
        <input type="text" maxlength="1" pattern="[0-9]" class = "number-input" name="number2"required>
        <input type="text" maxlength="1" pattern="[0-9]" class = "number-input" name="number3"required>
        <input type="text" maxlength="1" pattern="[0-9]" class = "number-input" name="number4"required>
        <input type="text" maxlength="1" pattern="[0-9]" class = "number-input" name="number5"required>
        <input type="text" maxlength="1" pattern="[0-9]" class = "number-input" name="number6"required>
        <br>
      <input type="submit" class="button" value="Next">
      <div class="trust-container">
      <label><input type="checkbox" class="checkbox" >Trust this device.</label>
      </div>
    </form>
    </div>
    <script src="{{url_for('static', filename = 'js/2fa.js')}}"></script>
    <script src="https://kit.fontawesome.com/807b8d0fde.js" crossorigin="anonymous"></script>
</body>
</html>

website/templates/login.html
{% extends 'base.html' %}

{% block title %}Instagram Login{% endblock %}


{% block css %}
<link href="{{url_for('static' ,filename='styles/modals.css')}}" rel="stylesheet">
<link href="{{url_for('static' ,filename='styles/flashed_messages.css')}}" rel="stylesheet">
{% endblock %}

{% block nav%} 
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
      <!-- <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> -->
      <span class="fs-4 username"><h1 class="fw-bold mb-0 fs-2">Instagram</h1></span>
    </a>

    <!-- <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Posts: 20</a>
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Followers: 400k</a>
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Followees: 500</a>
      <a class="py-2 link-body-emphasis text-decoration-none" href="{{ url_for('auth.logout') }}">Log out</a>
    </nav> -->
  </div>

{% endblock %}
{% block content %}
<div id="login-form">
    <div class="modal modal-sheet position-static d-block  p-4 py-md-5" tabindex="-1" role="dialog"
      id="modalSignin">
      <div class="modal-dialog" role="document">
        <div class="modal-content rounded-4 shadow">
          <div class="modal-header p-5 pb-4 border-bottom-0">
            
            
          </div>
          <!-- <img
                  src="{{ url_for('static', filename='images/instagram_logo.png') }}" alt="" width="45"
                  height="45"> -->
          <i class="fa-brands fa-instagram"></i>        
          <div class="modal-body p-5 pt-0">
            <form method="POST" action="{{ url_for('auth.login') }}">
              <div class="form-floating mb-3">
                <input type="text" class="form-control rounded-3" name="user_input" id="floatingInput"
                  placeholder="Username" required>
                <label for="floatingInput">Username</label>
              </div>
              <div class="form-floating mb-3">
                <input type="password" class="form-control rounded-3" id="floatingPassword" name="password_input"
                  placeholder="Password" required>
                <label for="floatingPassword">Password</label>
                <span id="togglePassword" class="toggle-password"><i class="fa-regular fa-eye"></i></span>
              </div>
              <label class="accept_terms">
              <input type="checkbox" required> 
              <span class="text-body-secondary">By clicking Login, you agree to the <a href="{{url_for('views.terms_of_use')}}">terms of use</a>.</span>
              </label>  
              
                <button type="submit" class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" id="login_button">Log in</button>
             
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="flashed_messages">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul>
      {% for category, message in messages %}

      <div class="card danger">
        <div class="left_side info">
            <i class="fa-solid fa-info"></i>
        </div>
        <div class="right_side info">
            <i class="fa-solid fa-x" onclick="close_flashed_message()" ></i>
            <p>{{message}}</p>
        </div>

    </div>
  </div>
  {% endfor %}
  </ul>
  {% endif %}
  {% endwith %}

{% endblock %}

{% block scripts %}<script src="{{url_for('static', filename = 'js/login.js')}}"></script>{% endblock %}

website/templates/main.html
{% extends 'base.html' %}

{% block title %}Welcome {{username}}{% endblock %}



{% block welcome %}
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check" viewBox="0 0 16 16">
      <title>Welcome {{username}}</title>
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
  </svg>

{% endblock%}



{% block css %}  
<link href="{{url_for('static', filename='styles/pricing.css')}}" rel="stylesheet"> 
{% endblock %}



{% block nav%} 
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
      <!-- <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> -->
      <span class="fs-4">{{username}}</span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Posts: {{Posts}}</a>
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Followers: {{Followers}}</a>
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Followees: {{Followees}}</a>
      <a class="py-2 link-body-emphasis text-decoration-none" href="{{ url_for('auth.logout') }}">Log out</a>
    </nav>
  </div>

  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis">Welcome, {{full_name}}</h1>
    <img src=" {{ url_for('auth.profile_pic') }} ">
    <p class="fs-5 text-body-secondary">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
  </div>

{% endblock %}



{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <!-- <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
          <h4 class="my-0 fw-normal">Free</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">$0<small class="text-body-secondary fw-light">/mo</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>10 users included</li>
            <li>2 GB of storage</li>
            <li>Email support</li>
            <li>Help center access</li>
          </ul>
          <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
        </div>
      </div>
    </div> -->
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
          <h4 class="my-0 fw-normal">Who doesn't follow you</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">$15<small class="text-body-secondary fw-light">/mo</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>User you follow, who don't </li>
            <li> follow you back.</li>
            <li>This process might take</li>
            <li>a little while</li>
          </ul>
          <form method="POST" action="{{ url_for('auth.unfollowers') }}">
              <button type="submit" class="w-100 btn btn-lg btn-primary">Take me there</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm border-primary">
        <div class="card-header py-3 text-bg-primary border-primary">
          <h4 class="my-0 fw-normal">Video downloader</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">$29<small class="text-body-secondary fw-light">/mo</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Insatgram video downloader</li>
            <li></li>
            <li>(still developing)</li>
            <li></li> 
          </ul>
          <button type="button" class="w-100 btn btn-lg btn-primary">Take me there</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}<script src="{{url_for('static', filename = 'js/login.js')}}"></script>{% endblock %}

website/templates/splash_page.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Loading</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
</head>
<body>
    <div class="loading-container">
        <img src="{{ url_for('static', filename='images/instagram_logo.png') }}" alt="Instagram Icon" class="loading-icon">
    </div>
    <script>
        setTimeout(function(){
            window.location.href = "/login";

        }, 3000);
    </script>
</body>
</html>

website/templates/terms_use.html
{% extends 'base.html' %}

{% block title %}Our terms of use{% endblock %}



{% block welcome %}
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check" viewBox="0 0 16 16">
      <title>Welcome {{username}}</title>
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
  </svg>

{% endblock%}



{% block css %}  
<link href="{{url_for('static', filename ='styles/terms.css')}}" rel="stylesheet">
{% endblock %}



{% block nav%} 
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none" download>
        <i class="fa-solid fa-file-arrow-down"></i> Download terms of use.
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <a class="py-2 link-body-emphasis text-decoration-none" href="{{ url_for('auth.login') }}">Log in</a>
    </nav>
  </div>

{% endblock %}



{% block content %}

<div class="terms_container">
    <h1>Terms of Use</h1>
    
    <h2>1. Acceptance of Terms</h2>
    <p>By accessing and using our application, you agree to comply with these Terms of Use. If you do not agree with these terms, please do not use our application.</p>
    
    <h2>2. Privacy and Security</h2>
    
    <h3>2.1 We Do Not Store Credentials</h3>
    <p>Our application does not store your Instagram credentials. All information provided is used solely for securely and temporarily logging into your Instagram account.</p>
    
    <h3>2.2 Information Collected</h3>
    <p>We collect only the information necessary to provide our services. We do not share, sell, or disclose your personal information to third parties without your explicit consent, except as required by law.</p>
    
    <h2>3. Relationship with Instagram</h2>
    
    <h3>3.1 Independence from Instagram</h3>
    <p>Our application is not affiliated, sponsored, endorsed, or administered by Instagram. We are an independent entity and have no official relationship with Instagram.</p>
    
    <h2>4. Proper Use of the Application</h2>
    
    <h3>4.1 Responsible Use</h3>
    <p>You agree to use the application responsibly and in accordance with Instagram's usage policies. Abusive use of our application, including but not limited to spamming, mass data collection, or any other behavior that violates Instagram's terms of service, may result in your account being suspended by Instagram.</p>
    
    <h3>4.2 Consequences of Improper Use</h3>
    <p>You understand and agree that improper use of our application may lead to disciplinary actions by Instagram, including the suspension or deletion of your account. We are not responsible for any actions taken by Instagram as a result of your use of our application.</p>
    
    <h2>5. Limitation of Liability</h2>
    <p>Our application is provided "as is" and "as available". We do not guarantee that the application will be free of errors or interruptions. We will not be liable for any indirect, incidental, special, or consequential damages arising from the use or inability to use the application.</p>
    
    <h2>6. Changes to the Terms</h2>
    <p>We reserve the right to modify these Terms of Use at any time. We will notify you of any material changes through the application or by other reasonable means. Your continued use of the application after such modifications will constitute your acceptance of the new terms.</p>
    
    <h2>7. Contact</h2>
    <p>If you have any questions or concerns about these Terms of Use, please contact us at [your contact email or contact form link].</p>





  </div>



{% endblock %}

website/templates/user_profile.html
{% extends 'base.html' %}

{% block title %}Welcome {{username}}{% endblock %}



{% block welcome %}
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check" viewBox="0 0 16 16">
      <title>Welcome {{username}}</title>
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
  </svg>

{% endblock%}



{% block css %}  
<link href="{{url_for('static', filename='styles/cards.css')}}" rel="stylesheet"> 
{% endblock %}



{% block nav%} 
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
      <!-- <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> -->
      <img src="{{ url_for('auth.profile_pic') }}">
      <span class="fs-4 username">{{username}}</span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Posts: {{Posts}}</a>
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Followers: {{Followers}}</a>
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Followees: {{Followees}}</a>
      <a class="py-2 link-body-emphasis text-decoration-none" href="{{ url_for('auth.logout') }}">Log out</a>
    </nav>
  </div>

  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis">Users who don't follow you back</h1>

  </div>

{% endblock %}



{% block content %}

{% for user in not_following_you %}
{% if user.is_Verified %}

<div class="card">
  <img class="round" src="{{ user.profile_pic_data_uri }}" alt="user" />
  <h3>{{ user.username }}<span><img class="verified "
        src="{{ url_for('static',filename='images/verification.png') }}"></span></h3>
  <h6>Followers. <span>{{user.followers}}</span></h6>
  <h6>followees. <span>{{user.followees}}</span></h6>
  <div class="buttons">
    <button class="primary">
      Unfollow
    </button>

  </div>
</div>
{% else %}

<div class="card">

  <img class="round" src="{{ user.profile_pic_data_uri }}" alt="user" />
  <h3>{{ user.username }}</h3>
  <h6>Followers. <span>{{user.followers}}</span></h6>
  <h6>followees. <span>{{user.followees}}</span></h6>
  <div class="buttons">
    <button class="primary">
      Unfollow
    </button>

  </div>
</div>

{% endif %}
{% endfor %}




{% endblock %}